[workspace]
members = [
    "crates/geo-polygonize-arrow",
    "crates/geo-polygonize-flatgeobuf",
    "crates/geo-polygonize-python",
    "xtask",
    "crates/geo-polygonize-core",
    "crates/geo-polygonize-wasm"
]
exclude = [
    "crates/geo-polygonize-core/benches/wasm_bench"
]
resolver = "2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
