// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeterminismOptions = { canonical_sort: boolean, canonical_ring_rotation: boolean, stable_tie_breaks: boolean, };
