// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainmentOptions } from "./ContainmentOptions";
import type { DeterminismOptions } from "./DeterminismOptions";
import type { DiagnosticsOptions } from "./DiagnosticsOptions";
import type { NodingOptions } from "./NodingOptions";
import type { ProvenanceOptions } from "./ProvenanceOptions";
import type { SnapStrategy } from "./SnapStrategy";
import type { TargetProfile } from "./TargetProfile";
import type { TilingOptions } from "./TilingOptions";
import type { ZOptions } from "./ZOptions";

export type PolygonizerOptions = { target: TargetProfile, node_input: boolean, snap_grid_size: number, extract_only_polygonal: boolean, snap_strategy: SnapStrategy, noding: NodingOptions, containment: ContainmentOptions, tiling: TilingOptions | null, z: ZOptions, determinism: DeterminismOptions, diagnostics: DiagnosticsOptions, provenance: ProvenanceOptions, input_profile_id: string | null, };
