// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProvenanceOptions = { enabled: boolean, include_boundary_line_ids: boolean, };
