[package]
name = "geo-polygonize-core"
version = "0.60.0"
edition = "2021"
description = "A native Rust port of the JTS/GEOS polygonization algorithm. Reconstruct valid polygons from a set of lines."
license = "MIT OR Apache-2.0"
readme = "../../README.md"

[dependencies]
geo = "0.32"
geo-types = "0.7"
rstar = "0.12"
rayon = { version = "1.10", optional = true }
robust = "1.2"
wide = "0.7"
log = "0.4"
thiserror = "1.0"
float_next_after = "1.0"
smallvec = "1.11"
geo-traits = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
humantime-serde = "1.1.1"
ts-rs = "12.0.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
multiversion = "0.8.0"

[dev-dependencies]
iai-callgrind = "0.16.1"
approx = "0.5"
criterion = "0.5"
rand = "0.8"
clap = { version = "4.5", features = ["derive"] }
geojson = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.5.0"
dhat = "0.3.3"

[features]
default = ["parallel"]
parallel = ["dep:rayon"]

[[bench]]
name = "polygonize_bench"
harness = false

[[example]]
name = "polygonize"
path = "../../examples/polygonize.rs"

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
web-time = "1.1.0"

[[bench]]
name = "extract_bench"
harness = false

[[bench]]
name = "hole_sort_bench"
harness = false

[[bench]]
name = "iai_bench"
harness = false
