[package]
name = "geo-polygonize-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
geo = "0.32"
geo-types = "0.7"
rstar = "0.12"
rayon = { version = "1.10", optional = true }
robust = "1.2"
wide = "0.7"
log = "0.4"
thiserror = "1.0"
float_next_after = "1.0"
smallvec = "1.11"

[dev-dependencies]
approx = "0.5"
criterion = "0.5"
rand = "0.8"
clap = { version = "4.5", features = ["derive"] }

[features]
default = ["parallel"]
parallel = ["dep:rayon"]

[[bench]]
name = "polygonize_bench"
harness = false
