/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_polygonizerwasmerror_free: (a: number, b: number) => void;
export const __wbg_wasmpolygonresult_free: (a: number, b: number) => void;
export const polygonize: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const polygonizeGeoArrowWithOptions: (a: number, b: number, c: any) => [number, number, number, number];
export const polygonizeWithOptions: (a: number, b: number, c: any) => [number, number, number, number];
export const polygonizeWithOptionsBuffer: (a: number, b: number, c: number, d: number, e: number, f: any, g: number, h: number) => [number, number, number];
export const polygonize_buffers: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number];
export const polygonize_geoarrow: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const polygonizerwasmerror_message: (a: number) => [number, number];
export const polygonizerwasmerror_name: (a: number) => [number, number];
export const polygonizerwasmerror_new: (a: number, b: number, c: number, d: number) => number;
export const wasmpolygonresult_coords_len: (a: number) => number;
export const wasmpolygonresult_coords_ptr: (a: number) => number;
export const wasmpolygonresult_diagnostics: (a: number) => any;
export const wasmpolygonresult_flat_line_ids_len: (a: number) => number;
export const wasmpolygonresult_flat_line_ids_ptr: (a: number) => number;
export const wasmpolygonresult_polygon_offsets_len: (a: number) => number;
export const wasmpolygonresult_polygon_offsets_ptr: (a: number) => number;
export const wasmpolygonresult_provenance: (a: number) => any;
export const wasmpolygonresult_ring_offsets_len: (a: number) => number;
export const wasmpolygonresult_ring_offsets_ptr: (a: number) => number;
export const wasmpolygonresult_stride: (a: number) => number;
export const polygonize_ffi: (a: number, b: number, c: number, d: number, e: number) => number;
export const polygonize_with_options_ffi: (a: number, b: number, c: number, d: number, e: number) => number;
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const initThreadPool: (a: number) => any;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_start_worker: (a: number) => void;
export const polygonize_result_free: () => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
