// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An exact finite coordinate. Every component is an IEEE-754 bit pattern.
 */
export type CoordinateFingerprintV1 = { x: string, y: string, z: string, };
