// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinateFingerprintV1 } from "./CoordinateFingerprintV1";

export type ErrorWitnessV1 = { ids: Array<string>, coordinate: CoordinateFingerprintV1 | null, };
