// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A first, field-level difference suitable for terse CI failures.
 */
export type FingerprintDiffV1 = { path: string, expected: unknown, actual: unknown, };
