// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodingBackend } from "./NodingBackend";
import type { NodingGuarantee } from "./NodingGuarantee";

export type NodingOptions = { backend: NodingBackend, guarantee: NodingGuarantee, };
