// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorWitnessV1 } from "./ErrorWitnessV1";

/**
 * A structured, stable error equality contract.
 */
export type NormalizedPolygonizeErrorV1 = { schema_version: number, family: string, code: string, stage: string, field: string | null, expected: string | null, actual: string | null, limit: string | null, observed: string | null, witness: ErrorWitnessV1 | null, };
