// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OutputFilterOptions = {
/**
 * Keep faces whose area is greater than or equal to this value.
 */
minimum_face_area?: number, };
