// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainmentOptions } from "./ContainmentOptions";
import type { DeterminismOptions } from "./DeterminismOptions";
import type { DiagnosticsOptions } from "./DiagnosticsOptions";
import type { NodingOptions } from "./NodingOptions";
import type { OutputFilterOptions } from "./OutputFilterOptions";
import type { ProvenanceOptions } from "./ProvenanceOptions";
import type { SnapStrategy } from "./SnapStrategy";

/**
 * The canonical configuration object for the `geo-polygonize` engine.
 *
 * This struct controls every aspect of the polygonization pipeline, including
 * topological robustness, feature output, containment policies, noding, and determinism.
 */
export type PolygonizerOptions = {
/**
 * Whether to robustly node the input before polygonization.
 *
 * Enable this for real-world linework where segment intersections may not
 * already exist as explicit vertices. This is slower than the fast path but
 * avoids missing faces and unresolved crossings.
 *
 * Default: `false`
 */
node_input: boolean,
/**
 * The snapping grid size used for vertex deduplication and noding operations.
 *
 * Vertices falling within the same grid cell are coalesced. A size of `0.0`
 * indicates exact floating-point evaluation without grid snapping.
 *
 * Default: `1e-10`
 */
snap_grid_size: number,
/**
 * Snap input segments to nearby vertices from exact-noded input linework before grid noding.
 *
 * A value of `0.0` disables pre-snap. This mirrors the CFB/Shapely
 * `snap(line, unary_union(all_lines), tolerance)` step closely enough to
 * close small CAD gaps before polygonization.
 *
 * Default: `0.0`
 */
pre_snap_tolerance: number,
/**
 * If `true`, only pure, outermost polygonal shells are returned.
 *
 * Floating dangles, internal cut-lines, or invalid rings will be discarded.
 *
 * Default: `false`
 */
extract_only_polygonal: boolean,
/**
 * Controls robust snap noding and output coordinate handling.
 *
 * See `SnapStrategy` for differences between strict `Grid` snapping and
 * Shapely/GEOS `GeosCompat` strategies.
 *
 * Default: `SnapStrategy::Grid`
 */
snap_strategy: SnapStrategy,
/**
 * Configures the noding engine backend and behavior.
 */
noding: NodingOptions,
/**
 * Configures how topological relationships (containment) are calculated
 * during face formation.
 */
containment: ContainmentOptions,
/**
 * Configuration for enforcing exact topological determinism.
 */
determinism: DeterminismOptions,
/**
 * Options for capturing diagnostic topology failures.
 */
diagnostics: DiagnosticsOptions,
/**
 * Options for mapping final faces back to original input geometry IDs.
 */
provenance: ProvenanceOptions,
/**
 * Optional application-level filtering applied after topology is established.
 */
output_filter: OutputFilterOptions,
/**
 * An optional identifier for the input dataset.
 */
input_profile_id?: string, };
