// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinateFingerprintV1 } from "./CoordinateFingerprintV1";
import type { ProvenanceFingerprintV1 } from "./ProvenanceFingerprintV1";
import type { RingFingerprintV1 } from "./RingFingerprintV1";

export type PolygonFingerprintV1 = { exterior: Array<CoordinateFingerprintV1>, interiors: Array<RingFingerprintV1>,
/**
 * Per-edge representative input IDs, encoded as fixed-width hex strings.
 */
exterior_edge_ids: Array<string>, provenance: ProvenanceFingerprintV1 | null, };
