// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coordinate precision used by the topology pipeline.
 */
export type PrecisionModel = { "type": "floating" } | { "type": "fixed_grid", grid_size: number, };
