// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProvenanceFingerprintV1 = {
/**
 * Complete source sets, never JSON numbers, so JavaScript cannot lose IDs.
 */
boundary_line_ids: Array<string>, input_profile_id: string | null, };
