// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DedupPolicy } from "./DedupPolicy";
import type { TileOwnershipPolicy } from "./TileOwnershipPolicy";

export type TilingOptions = { ownership_policy: TileOwnershipPolicy, dedup_policy: DedupPolicy, };
