// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoordinateFingerprintV1 } from "./CoordinateFingerprintV1";
import type { PolygonFingerprintV1 } from "./PolygonFingerprintV1";
import type { TopologyDiagnosticsFingerprintV1 } from "./TopologyDiagnosticsFingerprintV1";

/**
 * A versioned, structured canonical representation of a successful run.
 */
export type TopologyFingerprintV1 = { schema_version: number,
/**
 * The serialized canonical options object is part of the semantic contract.
 */
options: unknown, polygons: Array<PolygonFingerprintV1>, dangles: Array<Array<CoordinateFingerprintV1>>, cut_edges: Array<Array<CoordinateFingerprintV1>>, invalid_rings: Array<Array<CoordinateFingerprintV1>>, diagnostics: TopologyDiagnosticsFingerprintV1 | null, };
