// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Only topology-level diagnostics. Timings and work counters are deliberately excluded.
 */
export type TopologyDiagnosticsFingerprintV1 = { dangle_count: number, cut_edge_count: number, ring_count: number, shell_count: number, hole_count: number, unassigned_hole_count: number, unassigned_hole_area: string, invalid_ring_count: number, z_conflict_node_count: number, z_conflicting_line_ids: Array<string>, };
