// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ZPolicy } from "./ZPolicy";

export type ZOptions = { policy: ZPolicy,
/**
 * Z values at one XY node conflict when their difference exceeds this value.
 */
conflict_tolerance: number, };
