[package]
name = "geo-polygonize-wasm"
version = "0.29.2"
edition = "2021"
description = "WebAssembly bindings for geo-polygonize-core, a native Rust port of the JTS/GEOS polygonization algorithm."
license = "MIT OR Apache-2.0"
readme = "../../README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
geo-polygonize-core = { path = "../geo-polygonize-core", version = "0.29.2" }
wasm-bindgen = "0.2"
console_error_panic_hook = { version = "0.1.7", optional = true }
js-sys = "0.3"
geojson = "0.24"
serde_json = "1.0"
getrandom = { version = "0.2", features = ["js"] }
geo = "0.32"
wasm-bindgen-rayon = { version = "1.0", optional = true }
geo-traits = "0.3.0"
geoarrow = "0.7.0"
arrow-ipc = "57"
arrow = "57"
serde-wasm-bindgen = "0.6.5"

[features]
default = ["console_error_panic_hook"]
threads = ["wasm-bindgen-rayon", "geo-polygonize-core/parallel"]

[dev-dependencies]
wasm-bindgen-test = "0.3.36"
