// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IndexBackend } from "./IndexBackend";
import type { TouchPolicy } from "./TouchPolicy";

export type ContainmentOptions = { touch_policy: TouchPolicy, index_backend: IndexBackend, };
