// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodingBackend } from "./NodingBackend";
import type { SnapMode } from "./SnapMode";

export type NodingOptions = { backend: NodingBackend, snap_mode: SnapMode, };
