#!/bin/sh

echo "Running cargo fmt..."
cargo fmt --all

if [ $? -ne 0 ]; then
  echo "cargo fmt failed"
  # Exit to abort commit
  exit 1
fi

STAGED_RS_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.rs$' || true)

if [ -n "$STAGED_RS_FILES" ]; then
  echo "$STAGED_RS_FILES" | xargs git add
fi
