name: Enable automerge

on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    name: Enable automerge
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge
        uses: daneden/enable-automerge-action@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-author: "graydonpleasants"
          merge-method: "REBASE"
