---
name: Enable automerge

"on":
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    name: Enable automerge
    if: >
      github.event.pull_request.user.login == 'graydonpleasants' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      !github.event.pull_request.draft
    runs-on: ubuntu-latest

    steps:
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --auto \
            --rebase
