name: Publish Python Package

on:
  push:
    tags:
      - "v*"
      - "geo-polygonize-v*"

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --out dist

      - name: Sign macOS wheel
        if: runner.os == 'macOS'
        run: |
          python -m pip install wheel
          cd dist
          for whl in *.whl; do
            mkdir tmp_dir
            wheel unpack "$whl" -d tmp_dir
            rm "$whl"

            dir_name=$(ls tmp_dir)

            find "tmp_dir/$dir_name" -name "*.so" -exec codesign --force --sign - {} \;

            wheel pack "tmp_dir/$dir_name"
            rm -rf tmp_dir
          done

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist/*.whl

  publish-python:
    name: Publish Python Package
    needs: build-wheels
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true

      - name: Publish Wheels
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist

      - name: Install SBOM Tool
        run: pip install cyclonedx-bom

      - name: Generate SBOM
        run: cyclonedx-py requirements python/requirements.txt -o bom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-python
          path: bom.json