name: Publish to npm

on:
  push:
    tags:
      - "v*"
      - "geo-polygonize-v*"

jobs:
  publish-npm:
    name: Publish NPM Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Upgrade npm to support Trusted Publishing
        run: npm install -g npm@latest

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install dependencies
        run: npm ci

      - name: Build WebAssembly and TypeScript
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public --provenance

      - name: Generate SBOM
        uses: CycloneDX/gh-node-module-generatebom@v1
        with:
          path: './'
          output: './bom.json'

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-npm
          path: bom.json
