on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g. 0.4.2)"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please on push
        if: github.event_name == 'push'
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Run release-please with manual version
        if: github.event_name == 'workflow_dispatch'
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_PAT }}
          release-as: ${{ inputs.version }}
